# Conda environment used for Binder

name: labenv
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz=0.11.0
  - dash
  - ipywidgets
  - jupyterlab
  - jupyter-dash
  - lmfit
  - matplotlib
  - mkl
  - multiprocess
  - numba
  - numericalunits
  - numpy
  - pandas
  - paramiko
  - pip
  - pip:
    - dash_bootstrap_components
    - dash_daq
    - dash_trich_components
    - jupyterlab-spreadsheet-editor
    - molmass
  - plotly
  - pymc3
  - python=3.8.5
  - scipy
  - seaborn
  - theano-pymc
  - tqdm
  - uncertainties
  - voila